# This rule is not used by the project chinflux-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over chinflux.chinflux.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chinflux-operator
    app.kubernetes.io/managed-by: kustomize
  name: chinfluxbackup-admin-role
rules:
- apiGroups:
  - chinflux.chinflux.io
  resources:
  - chinfluxbackups
  verbs:
  - '*'
- apiGroups:
  - chinflux.chinflux.io
  resources:
  - chinfluxbackups/status
  verbs:
  - get
