# This rule is not used by the project chinflux-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the chinflux.chinflux.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chinflux-operator
    app.kubernetes.io/managed-by: kustomize
  name: chinfluxrestore-editor-role
rules:
- apiGroups:
  - chinflux.chinflux.io
  resources:
  - chinfluxrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chinflux.chinflux.io
  resources:
  - chinfluxrestores/status
  verbs:
  - get
