## Append samples of your project ##
resources:
- chinflux_v1alpha1_chinfluxcluster_single.yaml
- chinflux_v1alpha1_chinfluxcluster_cluster.yaml
- chinflux_v1alpha1_chinfluxcluster_tls.yaml
- chinflux_v1alpha1_chinfluxcluster_ha.yaml
- chinflux_v1alpha1_chinfluxbackup.yaml
- chinflux_v1alpha1_chinfluxrestore.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
