## Append samples of your project ##
resources:
- hyperbytedb_v1alpha1_hyperbytedbcluster_single.yaml
- hyperbytedb_v1alpha1_hyperbytedbcluster_cluster.yaml
- hyperbytedb_v1alpha1_hyperbytedbcluster_tls.yaml
- hyperbytedb_v1alpha1_hyperbytedbcluster_ha.yaml
- hyperbytedb_v1alpha1_hyperbytedbbackup.yaml
- hyperbytedb_v1alpha1_hyperbytedbrestore.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
