name: E2E Tests

on:
  push:
  pull_request:

concurrency:
  group: test-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: self-hosted
    container:
      image: golang:1.25-bookworm
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install Docker CLI
        run: curl -fsSL https://get.docker.com | sh

      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
